export const SET_IS_PENDING: string = 'TOGGLE_IS_PENDING';

export const NEXT_SLIDER_IMAGE: string = 'NEXT_SLIDER_IMAGE';

export const FETCH_SLIDER_IMAGES_START: string = 'FETCH_SLIDER_IMAGES_STARTED';

export const FETCH_SLIDER_IMAGES_SUCCESS: string = 'FETCH_SLIDER_IMAGES_SUCCESS';

export const FETCH_SLIDER_IMAGES_FAILURE: string = 'FETCH_SLIDER_IMAGES_FAILURE';